### PR TITLE
Add support for provisioning and basic synchronisation

### PR DESCRIPTION
**Pull request by Turakar**
There a two new methods introduced to the public part of the API:
- getNewDeviceUuid()
- finishNewDeviceRegistration()

The user first calls getNewDeviceUuid() and uses this uuid and a public key from a randomly generated IdentityKeyPair to create a QR code with the text:

tsdevice:/?uuid=[uuid]&pub_key=[public key Base64 encoded and URL safe]

Then the user calls finishNewDeviceRegistration() which blocks until the device is verified(that means scanned by the app). After that he can continue with setPreKeys().

The API is now also capable of serializing RequestMessages and deserializing the reply (contacts, groups and blocked lists). As contacts and group syncs are attachments, the code for reading them has to be written by your own. This can be done using the DeviceContactsInputStream or DeviceGroupsInputStream. I also fixed bugs regarding the library not being the primary device.

Tested and working:
- registration
- uploading of prekeys
- sending a message to somebody else and to the master device
- receiving messages from somebody else or the master device
- requesting and receiving a contacts list
- requesting and receiving a groups list
- requesting and receiving a blocked list
- using the library from the primary device

If you think that this is ready, I can sign the CLA.

### CODE REVIEW

**Comment by ayoub-benali** [comment]
Hi, `getNewDeviceUuid` is very handy.

Is there a reason that this PR is not merged ?

**Comment by moxie0** [comment]
Thanks for your interest @Turakar but a 1k line diff is a little big for your first contribution to the project.  I'd suggest starting with smaller contributions to get a feel for the project, we'd ultimately like to implement this functionality another way. Thanks again.

**Comment by moxie0** [comment]
Thanks @Trolldemorted but I think that's a bigger PR than we'd merge at this point. I'd recommend focusing on getting smaller PRs in first, getting a better feel for the code base, and getting a better understanding of all the complexities.

**Comment by micw** [comment]
> we'd ultimately like to implement this functionality another way

@moxie0 (How) was this functionally implemented meanwhile?

**Pull request closed without merging**
